package com.example.davaeth.zero_waste_cookbook_kotlin.repositories.interfaces.food_addons

import com.example.davaeth.zero_waste_cookbook_kotlin.database.models.food_addons.Region
import com.example.davaeth.zero_waste_cookbook_kotlin.repositories.interfaces.BaseRepository

interface RegionRepository: BaseRepository<Region>